[package]
name = "folio-markdown"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
folio-format = { path = "../folio-format" }
folio-input = { path = "../folio-input" }
folio-model = { path = "../folio-model" }
folio-text = { path = "../folio-text" }
serde.workspace = true
thiserror.workspace = true
